# Generated by Django 4.2 on 2023-04-17 08:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Hackathon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("background_image", models.ImageField(upload_to="hackathon_images")),
                ("hackathon_image", models.ImageField(upload_to="hackathon_images")),
                (
                    "submission_type",
                    models.CharField(
                        choices=[
                            ("image", "Image"),
                            ("file", "File"),
                            ("link", "Link"),
                        ],
                        max_length=5,
                    ),
                ),
                ("reward_prize", models.CharField(max_length=255)),
                ("start_datetime", models.DateTimeField()),
                ("end_datetime", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="Registration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("registration_datetime", models.DateTimeField(auto_now_add=True)),
                (
                    "hackathon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hackathon.hackathon",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Submission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("summary", models.TextField()),
                ("file", models.FileField(upload_to="hackathon_submissions")),
                ("link", models.URLField(null=True)),
                (
                    "image",
                    models.ImageField(null=True, upload_to="hackathon_submissions"),
                ),
                ("submission_datetime", models.DateTimeField(auto_now_add=True)),
                (
                    "registration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hackathon.registration",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="hackathon",
            constraint=models.CheckConstraint(
                check=models.Q(("start_datetime__lt", models.F("end_datetime"))),
                name="start_datetime_lt_end_datetime",
            ),
        ),
        migrations.AddConstraint(
            model_name="submission",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ("file__isnull", False),
                        ("link__isnull", False),
                        ("image__isnull", False),
                        _connector="OR",
                    )
                ),
                name="submission_type",
            ),
        ),
        migrations.AddConstraint(
            model_name="registration",
            constraint=models.UniqueConstraint(
                fields=("user", "hackathon"), name="unique_registration"
            ),
        ),
    ]
