# Generated by Django 4.2 on 2023-04-17 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("hackathon", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="submission",
            name="file",
            field=models.FileField(null=True, upload_to="hackathon_submissions"),
        ),
        migrations.AlterField(
            model_name="submission",
            name="registration",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="hackathon.registration",
                unique=True,
            ),
        ),
    ]
